services:
  web:
    image: nginx:latest
    environment:
      - COOLIFY_URL=https://chat.flexbiz.ro:80
    volumes:
      - ./livehelperchat/lhc_web:/code
      - ./conf/nginx/site-nodejs.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/mime.types:/etc/nginx/mime.types
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - php
      - php-cronjob
    networks:
      - code-network
    restart: always
  php:
    build: ./Dockerfiles/php
    image: remdex/livehelperchat-php:latest
    environment:
      ### Live Helper Chat settings
      - LHC_SECRET_HASH=${SERVICE_PASSWORD_SECRETHASH}
      # Should webhooks be enabled after install
      - LHC_WEBHOOKS_ENABLED=1
      ### DATABASE SETTINGS
      - MYSQL_DATABASE=${MYSQL_DATABASE:-lhc}
      - MYSQL_USER=${SERVICE_USER_MYSQL}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}
      ### NODE JS SETTINGS ###
      # This is port for frontend visitors for node js.
      - LHC_NODE_JS_PORT=443
      - REDIS_HOST=redis
      # Should visitors connect to NodeJS in secure way wss
      - LHC_NODE_JS_SECURE=1
      # Redis settings
      - REDIS_BACKEND=redis:6379
      - REDIS_BACKEND_DB=1
    volumes:
      - ./livehelperchat/lhc_web:/code
      - ./lhc-php-resque/lhcphpresque:/code/extension/lhcphpresque
      - ./NodeJS-Helper/nodejshelper:/code/extension/nodejshelper
      - ./conf/scripts:/scripts
      - ./conf/php-fpm/zz-lhc.conf:/usr/local/etc/php-fpm.d/zz-lhc.conf
    networks:
      - code-network
    restart: always
  cobrowse:
    build: ./Dockerfiles/cobrowse
    image: remdex/livehelperchat-cobrowse:latest
    ports:
      - 127.0.0.1:31130:31130
    networks:
      - code-network
    restart: always
  php-cronjob:
    build: ./Dockerfiles/cronjob
    image: remdex/livehelperchat-php-cronjob:latest
    environment:
      ### Live Helper Chat settings
      - LHC_SECRET_HASH=${SERVICE_PASSWORD_SECRETHASH}
      # Should webhooks be enabled after install
      - LHC_WEBHOOKS_ENABLED=1
      ### DATABASE SETTINGS
      - MYSQL_DATABASE=${MYSQL_DATABASE:-lhc}
      - MYSQL_USER=${SERVICE_USER_MYSQL}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}
      ### NODE JS SETTINGS ###
      # This is port for frontend visitors for node js.
      - LHC_NODE_JS_PORT=443
      - REDIS_HOST=redis
      # Should visitors connect to NodeJS in secure way wss
      - LHC_NODE_JS_SECURE=1
      # Redis settings
      - REDIS_BACKEND=redis:6379
      - REDIS_BACKEND_DB=1
    volumes:
      - ./livehelperchat/lhc_web:/code
      - ./lhc-php-resque/lhcphpresque:/code/extension/lhcphpresque
      - ./NodeJS-Helper/nodejshelper:/code/extension/nodejshelper
      - ./conf/scripts:/scripts
    networks:
      - code-network
    restart: always
  php-resque:
    build: ./Dockerfiles/php-resque
    image: remdex/livehelperchat-php-resque:latest
    environment:
      ### Live Helper Chat settings
      - LHC_SECRET_HASH=${SERVICE_PASSWORD_SECRETHASH}
      # Should webhooks be enabled after install
      - LHC_WEBHOOKS_ENABLED=1
      ### DATABASE SETTINGS
      - MYSQL_DATABASE=${MYSQL_DATABASE:-lhc}
      - MYSQL_USER=${SERVICE_USER_MYSQL}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}
      ### NODE JS SETTINGS ###
      # This is port for frontend visitors for node js.
      - LHC_NODE_JS_PORT=443
      - REDIS_HOST=redis
      # Should visitors connect to NodeJS in secure way wss
      - LHC_NODE_JS_SECURE=1
      # Redis settings
      - REDIS_BACKEND=redis:6379
      - REDIS_BACKEND_DB=1
    volumes:
      - ./livehelperchat/lhc_web:/code
      - ./lhc-php-resque/lhcphpresque:/code/extension/lhcphpresque
      - ./NodeJS-Helper/nodejshelper:/code/extension/nodejshelper
      - ./conf/scripts:/scripts
    networks:
      - code-network
    depends_on:
      - db
      - redis
    restart: always
  nodejshelper:
    build: ./Dockerfiles/nodejshelper
    image: remdex/livehelperchat-nodejshelper:latest
    environment:
      ### Live Helper Chat settings
      - LHC_SECRET_HASH=${SERVICE_PASSWORD_SECRETHASH}
      # Should webhooks be enabled after install
      - LHC_WEBHOOKS_ENABLED=1
      ### DATABASE SETTINGS
      - MYSQL_DATABASE=${MYSQL_DATABASE:-lhc}
      - MYSQL_USER=${SERVICE_USER_MYSQL}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}
      ### NODE JS SETTINGS ###
      # This is port for frontend visitors for node js.
      - LHC_NODE_JS_PORT=443
      - REDIS_HOST=redis
      # Should visitors connect to NodeJS in secure way wss
      - LHC_NODE_JS_SECURE=1
      # Redis settings
      - REDIS_BACKEND=redis:6379
      - REDIS_BACKEND_DB=1
    depends_on:
      - redis
    networks:
      - code-network
    restart: always
  redis:
    image: "redis:alpine"
    networks:
      - code-network
    restart: always
  db:
    image: mariadb
    environment:
      - TZ=UTC
      ### DATABASE SETTINGS
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_MYSQLROOT}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-lhc}
      - MYSQL_USER=${SERVICE_USER_MYSQL}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - code-network
    restart: always
networks:
  code-network:
    driver: bridge